config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="mainapp/index")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
]

mainapp/urls.py
from django.urls import path

from mainapp.apps import MainappConfig
from mainapp.views import (ContactsView, CoursesView, DocSiteView,
                           IndexView, LoginView, NewsView, NewsPageDetailView)

app_name = MainappConfig.name

urlpatterns = [
    path("index/", IndexView.as_view(), name="index"),
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("courses_list/", CoursesView.as_view(), name="courses_list"),
    path("doc_site/", DocSiteView.as_view(), name="doc_site"),
    path("login/", LoginView.as_view(), name="login"),
    path("news/", NewsView.as_view(), name="news"),
    path("news/<int:pk>/", NewsPageDetailView.as_view(), name="news_detail")
]

mainapp/models.py
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=256, verbose_name='Title')
    preambule = models.CharField(max_length=1024, verbose_name='Preambule')
    body = models.TextField(blank=True, null=True, verbose_name='Body')
    body_as_markdown = models.BooleanField(default=False, verbose_name='As markdown')
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Created')
    update = models.DateTimeField(auto_now = True, editable=False, verbose_name='Updated')
    deleted = models.BooleanField(default=False, verbose_name='Deleted')

    def __str__(self):
        return f"{self.pk}--->{self.title}"

    def delete(self):
        self.deleted = True
        self.save()

class CoursesManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class Courses(models.Model):
    objects = CoursesManager()
    name = models.CharField(max_length=256, verbose_name='Name')
    description = models.TextField(blank='True', null='True', verbose_name='Description')
    description_as_markdown = models.BooleanField(default=False, verbose_name='As markdown')
    cost = models.DecimalField(max_digits=8, decimal_places=2, default = 0, verbose_name='Cost')
    cover = models.CharField(max_length=25, default='no_image.svg', verbose_name='Cover')
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Created')
    updated = models.DateTimeField(auto_now=True, editable=False, verbose_name='Updated')
    deleted = models.BooleanField(default=False, verbose_name='Deleted')

    def __str__(self):
        return f"{self.pk}--->{self.name}"

    def delete(self):
        self.deleted = True
        self.save()


class Lesson(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name='Lesson number')
    title = models.CharField(max_length=256, verbose_name='Title')
    description = models.TextField(blank=True, null=True, verbose_name='Description')
    description_as_markdown=models.BooleanField(default=False, verbose_name='As markdown')
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Created')
    updated = models.DateTimeField(auto_now=True, verbose_name='Updated')
    deleted = models.BooleanField(default=False, verbose_name='Deleted')

    def __str__(self):
        return f"{self.course.name} {self.num} {self.title}"

    def delete(self):
        self.deleted = True
        self.save()

    class Meta:
        ordering = ('course', 'num')


class CourseTeachers(models.Model):
    course = models.ManyToManyField(Courses)
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "{0:0>3} {1} {2}".format(self.pk, self.name_second, self.name_first)

    def delete(self, *args):
        self.deleted = True
        self.save()

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, TemplateView
from mainapp.models import News

# Create your views here.


class IndexView(TemplateView):
    template_name = "mainapp/index.html"


class ContactsView(TemplateView):
    template_name = "mainapp/contacts.html"


class CoursesView(TemplateView):
    template_name = "mainapp/courses.html"


class DocSiteView(TemplateView):
    template_name = "mainapp/doc_site.html"


class LoginView(TemplateView):
    template_name = "mainapp/login.html"


class NewsView(TemplateView):
    template_name = "mainapp/news.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["news_list"] = News.objects.all()
        return context
    

class NewsPageDetailView(TemplateView):
    template_name = 'mainapp/news_detail.html'

    def get_context_data(self, pk, **kwargs):
        context = super().get_context_data(**kwargs)
        context["news_object"] = get_object_or_404(News, pk = pk)
        return context
    

mainapp/templates/includes/inc_main_menu.html
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'mainapp:news' %}">Новости</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'mainapp:courses_list'%}">Курсы</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                Профиль
            </a>
            <div class="dropdown-menu" aria-labelledby="ddProfile">
                <a class="dropdown-item" href="#">Редактировать профиль</a>
                <a class="dropdown-item" href="#">Мои курсы</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Модерация</a>
                <a class="dropdown-item" href="#">Административный раздел</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Выход</a>
            </div>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'mainapp:contacts' %}">Контакты</a>
        </li>
    </ul>
    <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
</div>

mainapp/templates/mainapp/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static '/css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static '/css/fontawesome.all.min.css' %}">

    <title>
        {% block title %}
        Welcome to Braniac!
        {% endblock title %}
    </title>

</head>

<body>



    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'mainapp:index' %}">
                <img src="{% static '/img/logo.png' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            {% include 'includes/inc_main_menu.html' %}

        </div>
    </nav>


    
    {% block container %}
        
    {% endblock container %}
        


    <!-- Footer -->

    <div class="container-lg mt-auto">
        <hr>
        <div class="row justify-content-center">
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Braniac</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href="{% url 'mainapp:index' %}">Домашняя</a></li>
                    <li><a href="{% url 'mainapp:news' %}">Новости</a></li>
                    <li><a href="{% url 'mainapp:login' %}">Войти</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Полезное</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href="#">Положения &amp; Условия</a></li>
                    <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
                    <li><a href="#">Документация по API</a></li>
                    <li><a href="doc_site.html">Документация по сайту</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Мы в социальных сетях</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
                </div>
                </p>
                <p>
                    <strong>Наше приложение</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-windows fa-2x"></i></a></div>
                </div>
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div>
                <p><small>&copy; GeekBrains 2021</small></p>
            </div>
        </div>
    </div>

    <!-- /Footer -->




    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="{% static '/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static '/js/popper.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static '/js/Chart.min.js' %}"></script>

    <!-- FontAwesome -->
    <script src="{% static '/js/fontawesome.all.min.js' %}"></script>



</body>

</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load mainapp_tags %}

{% block container %}

<div class="container-md">

  <p>
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Наши контакты</h1>
      <p class="lead">Обязательно свяжитесь с нами! Ваш комфорт - наша забота.</p>
    </div>
  </div>
  </p>
  <p>
  <div class="row justify-content-around mt-n2">
    
    <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
      <div class="card h-100 shadow">
        <div class="card-body">
          <div style="position:relative;overflow:hidden;"><a                 href="https://yandex.ru/maps/org/petropavlovskaya_krepost/146720535721/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:0px;">Петропавловская крепость</a><a                 href="https://yandex.ru/maps/2/saint-petersburg/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:14px;">Достопримечательность в                 Санкт‑Петербурге</a><a                 href="https://yandex.ru/maps/2/saint-petersburg/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:28px;">Музей в Санкт‑Петербурге</a><iframe                 src="https://yandex.ru/map-widget/v1/-/CCUAZHcrhA" width="100%" height="300" frameborder="0"                 allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>             </div>
          <h5 class="card-title">Санкт‑Петербург</h5>
          <p class="card-text">
          <ul class="list-unstyled">
            <li>Телефон</li>
            <li><strong>+7-999-11-11111</strong></li>
          </ul>
          <ul class="list-unstyled">
            <li>Email</li>
            <li><strong>{{'geeklab@spb.ru'|email_to_link}}</strong></li>
          </ul>
          <ul class="list-unstyled">
            <li>Адрес</li>
            <li><strong>территория Петропавловская крепость, 3Ж</strong></li>
          </ul>
          </p>
        </div>
      </div>
    </div>
    
    <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
      <div class="card h-100 shadow">
        <div class="card-body">
          <div style="position:relative;overflow:hidden;"><a                 href="https://yandex.ru/maps/org/kazanskiy_kreml/95813866834/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:0px;">Казанский Кремль</a><a                 href="https://yandex.ru/maps/43/kazan/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:14px;">Музей в Казани</a><a                 href="https://yandex.ru/maps/43/kazan/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:28px;">Достопримечательность в Казани</a><iframe                 src="https://yandex.ru/map-widget/v1/-/CCUAZHX3xB" width="100%" height="300" frameborder="0"                 allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>             </div>
          <h5 class="card-title">Казань</h5>
          <p class="card-text">
          <ul class="list-unstyled">
            <li>Телефон</li>
            <li><strong>+7-999-22-22222</strong></li>
          </ul>
          <ul class="list-unstyled">
            <li>Email</li>
            <li><strong>{{'geeklab@kz.ru'| email_to_link}}</strong></li>
          </ul>
          <ul class="list-unstyled">
            <li>Адрес</li>
            <li><strong>территория Кремль, 11, Казань, Республика Татарстан, Россия</strong></li>
          </ul>
          </p>
        </div>
      </div>
    </div>
    
    <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
      <div class="card h-100 shadow">
        <div class="card-body">
          <div style="position:relative;overflow:hidden;"><a                 href="https://yandex.ru/maps/org/sobor_pokrova_presvyatoy_bogoroditsy_na_rvu/175159255687/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:0px;">Собор Покрова Пресвятой Богородицы на                 Рву</a><a href="https://yandex.ru/maps/213/moscow/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:14px;">Музей в Москве</a><iframe                 src="https://yandex.ru/map-widget/v1/-/CCUAZHh9kD" width="100%" height="300" frameborder="0"                 allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>             </div>
          <h5 class="card-title">Москва</h5>
          <p class="card-text">
          <ul class="list-unstyled">
            <li>Телефон</li>
            <li><strong>+7-999-33-33333</strong></li>
          </ul>
          <ul class="list-unstyled">
            <li>Email</li>
            <li><strong>{{ 'geeklab@msk.ru'|email_to_link }}</strong></li>
          </ul>
          <ul class="list-unstyled">
            <li>Адрес</li>
            <li><strong>Красная площадь, 7, Москва, Россия</strong></li>
          </ul>
          </p>
        </div>
      </div>
    </div>
    
  </div>
  </p>

</div>

{% endblock container %}

mainapp/templates/mainapp/courses.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}

    <div class="container-md">

        <div class="row justify-content-center mt-3">
            

                    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                    <a href="#">
                        <img src="{% static '/img/course001.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title text-center">Web Python</h5>
                        </div>
                    </a>
                    </div>

            

                    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                    <a href="#">
                        <img src="{% static '/img/course002.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title text-center">Web Golang</h5>
                        </div>
                    </a>
                    </div>

            

                    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                    <a href="#">
                        <img src="{% static '/img/course003.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title text-center">Web JavaScript</h5>
                        </div>
                    </a>
                    </div>

            

                    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                    <a href="#">
                        <img src="{% static '/img/course004.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title text-center">Web Java</h5>
                        </div>
                    </a>
                    </div>

            

                    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                    <a href="#">
                        <img src="{% static '/img/course005.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title text-center">Web PHP</h5>
                        </div>
                    </a>
                    </div>

            

                    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                    <a href="#">
                        <img src="{% static '/img/course006.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title text-center">Python AI</h5>
                        </div>
                    </a>
                    </div>

            

                    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                    <a href="#">
                        <img src="{% static '/img/course007.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title text-center">DevOps</h5>
                        </div>
                    </a>
                    </div>

            
        </div>
        <div class="row justify-content-center align-items-center mt-3 mb-n3">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
                </ul>
            </nav>
        </div>

    </div>

{% endblock container %}

mainapp/templates/mainapp/doc_site.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">

    <!-- ChartJS -->
    <link rel="stylesheet" href="/css/Chart.min.css">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="/css/fontawesome.all.min.css">

    <title>Документация по сайту</title>
</head>

<body>



    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="index.html">
                <img src="/img/logo.png" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item ">
                        <a class="nav-link" href="news.html">Новости</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="courses_list.html">Курсы</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Профиль
                        </a>
                        <div class="dropdown-menu" aria-labelledby="ddProfile">
                            <a class="dropdown-item" href="#">Редактировать профиль</a>
                            <a class="dropdown-item" href="#">Мои курсы</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Модерация</a>
                            <a class="dropdown-item" href="#">Административный раздел</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Выход</a>
                        </div>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="contacts.html">Контакты</a>
                    </li>
                </ul>
                <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
            </div>
        </div>
    </nav>





    <div class="container-md">

        
<div class="row justify-content-center align-items-center mt-3">
  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        Документация по сайту
      </div>
      <div class="card-body">

        <h5 class="card-title">CSS-стили</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/" target="_blank">Bootstrap
              v4.6</a></li>
          <li><a href="https://bootswatch.com/lumen/" target="_blank">Bootstrap theme: Lumen</a></li>
        </ul>
        </p>

        <h5 class="card-title">Иконки</h5>
        <p class="card-text">
          <a href="https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use">FontAwesome 5.15.3</a>
        </p>

        <h5 class="card-title">Графики</h5>
        <p class="card-text">
          <a href="https://www.chartjs.org/">ChartJS</a>
        </p>

        <h5 class="card-title">Графика</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://www5.flamingtext.com/" target="_blank" rel="noopener noreferrer">Логотип by
              flamingtext.com</a></li>
          <li><a href="https://www.pexels.com/ru-ru" target="_blank" rel="noopener noreferrer">Фотографии by
              pexels.com</a>. Все изображения распространяются под бесплатной лицензией. Для страницы обзоров фотографии
            должны быть с соотношением сторон кратным 2.912 (например, 1920x659)</li>
          <li><a href="https://getavataaars.com/" target="_blank" rel="noopener noreferrer">Аватарки пользователей by
              getavataaars.com</a></li>
        </ul>
        </p>

      </div>
    </div>
  </div>
</div>


    </div>





    <!-- Footer -->

    <div class="container-lg mt-auto">
        <hr>
        <div class="row justify-content-center">
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Braniac</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href="index.html">Домашняя</a></li>
                    <li><a href="news.html">Новости</a></li>
                    <li><a href="login.html">Войти</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Полезное</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href="#">Положения &amp; Условия</a></li>
                    <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
                    <li><a href="#">Документация по API</a></li>
                    <li><a href="doc_site.html">Документация по сайту</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Мы в социальных сетях</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
                </div>
                </p>
                <p>
                    <strong>Наше приложение</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-windows fa-2x"></i></a></div>
                </div>
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div>
                <p><small>&copy; GeekBrains 2021</small></p>
            </div>
        </div>
    </div>

    <!-- /Footer -->




    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="/js/jquery-3.6.0.min.js"></script>
    <script src="/js/popper.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>

    <!-- ChartJs -->
    <script src="/js/Chart.min.js"></script>

    <!-- FontAwesome -->
    <script src="/js/fontawesome.all.min.js"></script>



</body>

</html>

mainapp/templates/mainapp/news.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}

<div class="container-md">

  <div class="row">

    <div class="col-lg-8">
      
      {% for news in news_list %}
      <div class="card my-2">
        <div class="card-body">
          <h5 class="card-title">{{ news.title }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ news.created | date:"d M Y"}}</h6>
          <p class="card-text">{{ news.preambule }}</p>
          <a href="{% url 'mainapp:news_detail' news.pk %}" class="card-link">Побробнее</a>
        </div>
      </div>
      {% endfor %}
            
    </div>

    <div class="col-lg-4">
      <div class="card my-2 sticky-top">
        <div class="card-header">
          Фильтры
        </div>
        <div class="card-body">
          <form action="">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Дата от...</span>
              </div>
              <input type="date" class="form-control" name="dateFrom">
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Дата до...</span>
              </div>
              <input type="date" class="form-control" name="dateTo">
            </div>

            <button type="submit" class="btn btn-primary btn-block">Фильтровать</button>
          </form>
        </div>
      </div>
    </div>

  </div>

  <div class="row justify-content-center align-items-center mt-3 mb-n3">
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
      </ul>
    </nav>
  </div>

</div>

{%endblock container%}

mainapp/templates/mainapp/news_detail.html
{% extends 'mainapp/base.html' %}

{% block title %}
{{ news_object.title}}
{% endblock title %}

{% block container %}
<div class="row justify-content-center pt-3">
    <div class="col-md-12 col-lg-8">
        <div class="card shadow">
            <div class="card-body">
                <h5 class="card-title">{{ news_object.title }}</h5>
                <p class="card-text">
                    {{ news_object.body }}
                </p>
                <a href="{% url 'mainapp:news' %}"
                class="btn btn-primary">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock container %}